name: agconnect_core_upgrade
description: Flutter plugin for AppGallery Connect Core SDK, Fork of Huawei agconnect_core (patched for Flutter v2 embedding & AGP 8+)
version: 1.9.0+301
homepage: https://www.a5dr.com

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.huawei.agconnectcore_upgrade
        pluginClass: AGConnectCorePlugin
      ios:
        pluginClass: AGConnectCorePlugin
